version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SERVER_URL: http://localhost:3001
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
